---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - nodes
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - issuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - bind
  - create
  - delete
  - escalate
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - seaweed.seaweedfs.com
  resources:
  - buckets
  - s3credentials
  - s3identities
  - s3oidcproviders
  - s3policies
  - s3policybindings
  - seaweedcsidrivers
  - seaweeds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - seaweed.seaweedfs.com
  resources:
  - buckets/finalizers
  - s3credentials/finalizers
  - s3identities/finalizers
  - s3oidcproviders/finalizers
  - s3policies/finalizers
  - s3policybindings/finalizers
  - seaweedcsidrivers/finalizers
  verbs:
  - update
- apiGroups:
  - seaweed.seaweedfs.com
  resources:
  - buckets/status
  - s3credentials/status
  - s3identities/status
  - s3oidcproviders/status
  - s3policies/status
  - s3policybindings/status
  - seaweedcsidrivers/status
  - seaweeds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - seaweed.seaweedfs.com
  resources:
  - resourcereferencegrants
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotcontents
  - volumesnapshots
  verbs:
  - get
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - csidrivers
  - storageclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - csinodes
  - volumeattachments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
