// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeaweedfsCluster) DeepCopyInto(out *SeaweedfsCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeaweedfsCluster.
func (in *SeaweedfsCluster) DeepCopy() *SeaweedfsCluster {
	if in == nil {
		return nil
	}
	out := new(SeaweedfsCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeaweedfsCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeaweedfsClusterList) DeepCopyInto(out *SeaweedfsClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SeaweedfsCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeaweedfsClusterList.
func (in *SeaweedfsClusterList) DeepCopy() *SeaweedfsClusterList {
	if in == nil {
		return nil
	}
	out := new(SeaweedfsClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeaweedfsClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeaweedfsClusterSpec) DeepCopyInto(out *SeaweedfsClusterSpec) {
	*out = *in
	out.Master = in.Master
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]SeaweedfsVolumeSpec, len(*in))
		copy(*out, *in)
	}
	out.Filer = in.Filer
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeaweedfsClusterSpec.
func (in *SeaweedfsClusterSpec) DeepCopy() *SeaweedfsClusterSpec {
	if in == nil {
		return nil
	}
	out := new(SeaweedfsClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeaweedfsClusterStatus) DeepCopyInto(out *SeaweedfsClusterStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeaweedfsClusterStatus.
func (in *SeaweedfsClusterStatus) DeepCopy() *SeaweedfsClusterStatus {
	if in == nil {
		return nil
	}
	out := new(SeaweedfsClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeaweedfsFilerSpec) DeepCopyInto(out *SeaweedfsFilerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeaweedfsFilerSpec.
func (in *SeaweedfsFilerSpec) DeepCopy() *SeaweedfsFilerSpec {
	if in == nil {
		return nil
	}
	out := new(SeaweedfsFilerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeaweedfsMasterSpec) DeepCopyInto(out *SeaweedfsMasterSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeaweedfsMasterSpec.
func (in *SeaweedfsMasterSpec) DeepCopy() *SeaweedfsMasterSpec {
	if in == nil {
		return nil
	}
	out := new(SeaweedfsMasterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeaweedfsVolumeSpec) DeepCopyInto(out *SeaweedfsVolumeSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeaweedfsVolumeSpec.
func (in *SeaweedfsVolumeSpec) DeepCopy() *SeaweedfsVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(SeaweedfsVolumeSpec)
	in.DeepCopyInto(out)
	return out
}
