/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package helm verifies that hand-maintained Helm chart artifacts stay in
// sync with the kubebuilder/kustomize source of truth in config/. The
// chart's RBAC YAML is hand-edited (not auto-generated by helm-crd-copy
// or any other Make target), so kubebuilder marker changes silently
// regenerate config/rbac/role.yaml without touching deploy/helm. This
// drift caused issue #223: the operator ran with the chart's stale RBAC
// and could not List its own Bucket CR.
package helm

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"testing"

	rbacv1 "k8s.io/api/rbac/v1"
	"k8s.io/apimachinery/pkg/util/yaml"
)

// TestHelmManagerRoleIsSupersetOfKustomize fails when any (apiGroup,
// resource, verb) triple granted by config/rbac/role.yaml is missing from
// the chart-rendered manager ClusterRole. Extra rules in the Helm chart
// (e.g., the conditional ServiceMonitor block) are allowed; missing
// rules are not.
func TestHelmManagerRoleIsSupersetOfKustomize(t *testing.T) {
	root := projectRoot(t)

	helmRules := helmManagerRules(t, filepath.Join(root, "deploy", "helm"))
	kustomizeRules := kustomizeManagerRules(t, filepath.Join(root, "config", "rbac", "role.yaml"))

	helmTriples := flattenRules(helmRules)
	kustomizeTriples := flattenRules(kustomizeRules)

	var missing []ruleTriple
	for triple := range kustomizeTriples {
		if !helmTriples[triple] {
			missing = append(missing, triple)
		}
	}
	if len(missing) == 0 {
		return
	}

	sort.Slice(missing, func(i, j int) bool {
		return missing[i].String() < missing[j].String()
	})
	t.Errorf("Helm chart manager-role is missing %d (apiGroup, resource, verb) triple(s) granted by config/rbac/role.yaml.", len(missing))
	t.Errorf("Update deploy/helm/templates/rbac/role.yaml to include these rules:")
	for _, m := range missing {
		t.Errorf("  - %s", m)
	}
	t.Errorf("Reason this matters: kubebuilder regenerates config/rbac/role.yaml from controller markers, but the Helm chart's RBAC is hand-maintained. Without parity, fresh Helm installs deploy with stale permissions and the operator fails to watch its own resources at startup (see issue #223).")
}

// ruleTriple is one (apiGroup, resource, verb) grant. PolicyRule is a
// cross-product over its three slices, so we explode each rule into the
// triples it actually authorizes and compare those — comparing
// PolicyRule structs directly would falsely report drift on cosmetic
// differences like rule ordering or a single rule split into two for
// readability.
type ruleTriple struct {
	apiGroup string
	resource string
	verb     string
}

func (t ruleTriple) String() string {
	g := t.apiGroup
	if g == "" {
		g = `""`
	}
	return fmt.Sprintf(`apiGroups=%s resources=%s verbs=%s`, g, t.resource, t.verb)
}

func flattenRules(rules []rbacv1.PolicyRule) map[ruleTriple]bool {
	out := map[ruleTriple]bool{}
	for _, r := range rules {
		for _, g := range r.APIGroups {
			for _, res := range r.Resources {
				for _, v := range r.Verbs {
					out[ruleTriple{apiGroup: g, resource: res, verb: v}] = true
				}
			}
		}
	}
	return out
}

func helmManagerRules(t *testing.T, chartDir string) []rbacv1.PolicyRule {
	t.Helper()
	// Render with the chart's default values — exactly what
	// `helm install seaweedfs/seaweedfs-operator` produces for a
	// fresh user. The previous version of this test rendered with
	// every feature toggle enabled (e.g., serviceMonitor.enabled=true)
	// to compare against the unconditional kustomize role; that
	// masked the bug behind the comment on issue #223 — users hit
	// the operator running with default-Helm RBAC, and any rule
	// gated behind a values flag is missing for them. The kustomize
	// role represents what the operator's controller code might
	// actually request at runtime; the chart's default render must
	// be a superset of that, regardless of which optional features
	// the operator is using locally. RBAC scoped to "only granted
	// when feature X is enabled" is fine in principle, but it has
	// to be tied to a runtime signal the operator code itself
	// observes — not a Helm value the operator binary knows nothing
	// about.
	cmd := exec.Command("helm", "template", "drift-test", chartDir)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		// Distinguish a missing helm binary (legitimate skip on a
		// dev machine without helm) from a chart render error
		// (genuine regression that must fail the build).
		if errors.Is(err, exec.ErrNotFound) {
			t.Skipf("helm not found in PATH; skipping RBAC parity test: %v", err)
		}
		t.Fatalf("helm template failed: %v\nstderr: %s", err, stderr.String())
	}
	return findManagerRoleRules(t, stdout.Bytes(), "drift-test")
}

func findManagerRoleRules(t *testing.T, rendered []byte, releaseName string) []rbacv1.PolicyRule {
	t.Helper()
	dec := yaml.NewYAMLOrJSONDecoder(bytes.NewReader(rendered), 4096)
	wantName := releaseName + "-seaweedfs-operator-manager-role"
	for {
		var role rbacv1.ClusterRole
		if err := dec.Decode(&role); err != nil {
			if errors.Is(err, io.EOF) {
				break
			}
			// Skip docs that don't shape into a ClusterRole. Decode
			// returns errors for malformed YAML too, but the chart
			// is rendered fresh in the same test invocation and
			// already validated by helm template's own pass.
			continue
		}
		if role.Kind == "ClusterRole" && role.Name == wantName {
			return role.Rules
		}
	}
	t.Fatalf("no ClusterRole named %q found in rendered chart output (helm release: %q)", wantName, releaseName)
	return nil
}

func kustomizeManagerRules(t *testing.T, path string) []rbacv1.PolicyRule {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	var role rbacv1.ClusterRole
	if err := yaml.Unmarshal(data, &role); err != nil {
		t.Fatalf("unmarshal %s: %v", path, err)
	}
	if role.Kind != "ClusterRole" {
		t.Fatalf("%s: expected kind ClusterRole, got %q", path, role.Kind)
	}
	return role.Rules
}

// projectRoot finds the operator repo root by walking up from the test
// file's directory until it sees a go.mod. Lets the test run from any
// cwd (`go test ./test/helm/...` or invocation from the repo root).
func projectRoot(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller(0) failed")
	}
	dir := filepath.Dir(thisFile)
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatalf("could not find project root from %s", filepath.Dir(thisFile))
		}
		dir = parent
	}
}
