/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package helm verifies that hand-maintained Helm chart artifacts stay in
// sync with the kubebuilder/kustomize source of truth in config/. The
// chart's RBAC YAML is hand-edited (not auto-generated by helm-crd-copy
// or any other Make target), so kubebuilder marker changes silently
// regenerate config/rbac/role.yaml without touching deploy/helm. When
// that drift happens, fresh Helm installs deploy with stale permissions
// and the operator fails to watch its own resources at startup.
package helm

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strings"
	"testing"

	rbacv1 "k8s.io/api/rbac/v1"
	"k8s.io/apimachinery/pkg/util/yaml"
)

// TestHelmManagerRoleIsSupersetOfKustomize fails when any (apiGroup,
// resource, verb) triple granted by config/rbac/role.yaml is missing from
// the chart-rendered manager ClusterRole. Extra rules in the Helm chart
// (e.g., the conditional ServiceMonitor block) are allowed; missing
// rules are not.
//
// config/rbac/role.yaml is generated from every controller's markers,
// including the SeaweedCSIDriver controller's, so the chart is rendered
// with csiDriver.enabled=true: that is the state in which the manager
// registers every controller the kustomize role accounts for.
// TestHelmManagerRoleCSIGate covers the default render.
func TestHelmManagerRoleIsSupersetOfKustomize(t *testing.T) {
	root := projectRoot(t)

	helmRules := helmManagerRules(t, filepath.Join(root, "deploy", "helm"), "--set", "csiDriver.enabled=true")
	kustomizeRules := kustomizeManagerRules(t, filepath.Join(root, "config", "rbac", "role.yaml"))

	missing := missingTriples(flattenRules(kustomizeRules), flattenRules(helmRules))
	if len(missing) == 0 {
		return
	}

	t.Errorf("Helm chart manager-role is missing %d (apiGroup, resource, verb) triple(s) granted by config/rbac/role.yaml.", len(missing))
	t.Errorf("Update deploy/helm/templates/rbac/role.yaml to include these rules:")
	for _, m := range missing {
		t.Errorf("  - %s", m)
	}
	t.Errorf("Reason this matters: kubebuilder regenerates config/rbac/role.yaml from controller markers, but the Helm chart's RBAC is hand-maintained. Without parity, fresh Helm installs deploy with stale permissions and the operator fails to watch its own resources at startup.")
}

// csiControllerFile declares the only controller the manager registers
// conditionally, on ENABLE_CSI_DRIVER (see cmd/main.go). The chart sets
// that variable from csiDriver.enabled and gates the controller's RBAC on
// the same value, so a default install does not hold cluster-wide
// bind/escalate, CSIDriver, node, or PersistentVolume grants it cannot use.
const csiControllerFile = "seaweedcsidriver_controller.go"

// TestHelmManagerRoleCSIGate pins both sides of the csiDriver.enabled RBAC
// gate against the kubebuilder markers in internal/controller:
//
//   - the default render must still grant every triple declared by the
//     always-on controllers, so the gate cannot swallow a rule some other
//     controller needs (a marker added elsewhere for a resource the CSI
//     block currently owns shows up here);
//   - the default render must grant none of the triples only the CSI
//     controller declares, so the gate stays a gate.
//
// Rendering with the flag on is covered by
// TestHelmManagerRoleIsSupersetOfKustomize.
func TestHelmManagerRoleCSIGate(t *testing.T) {
	root := projectRoot(t)
	chartDir := filepath.Join(root, "deploy", "helm")

	csiTriples, otherTriples := controllerMarkerTriples(t, filepath.Join(root, "internal", "controller"))
	if len(csiTriples) == 0 || len(otherTriples) == 0 {
		t.Fatalf("parsed %d CSI and %d non-CSI rbac markers from internal/controller; expected both non-empty", len(csiTriples), len(otherTriples))
	}
	defaultTriples := flattenRules(helmManagerRules(t, chartDir))

	if missing := missingTriples(otherTriples, defaultTriples); len(missing) > 0 {
		t.Errorf("Default Helm render is missing %d triple(s) declared by controllers that run regardless of ENABLE_CSI_DRIVER:", len(missing))
		for _, m := range missing {
			t.Errorf("  - %s", m)
		}
		t.Errorf("Move these out of the csiDriver.enabled block in deploy/helm/templates/rbac/role.yaml (or add them); a marker outside %s now needs them.", csiControllerFile)
	}

	csiOnly := map[ruleTriple]bool{}
	for triple := range csiTriples {
		if !otherTriples[triple] {
			csiOnly[triple] = true
		}
	}
	var leaked []ruleTriple
	for triple := range csiOnly {
		if defaultTriples[triple] {
			leaked = append(leaked, triple)
		}
	}
	if len(leaked) > 0 {
		sort.Slice(leaked, func(i, j int) bool { return leaked[i].String() < leaked[j].String() })
		t.Errorf("Default Helm render grants %d triple(s) only the SeaweedCSIDriver controller declares; they belong inside the csiDriver.enabled block in deploy/helm/templates/rbac/role.yaml:", len(leaked))
		for _, l := range leaked {
			t.Errorf("  - %s", l)
		}
	}
}

// missingTriples returns, sorted, every triple in want that got lacks.
func missingTriples(want, got map[ruleTriple]bool) []ruleTriple {
	var missing []ruleTriple
	for triple := range want {
		if !got[triple] {
			missing = append(missing, triple)
		}
	}
	sort.Slice(missing, func(i, j int) bool { return missing[i].String() < missing[j].String() })
	return missing
}

// rbacMarker matches one `// +kubebuilder:rbac:groups=...,resources=...,verbs=...`
// line. Only the three fields the manager role is generated from are
// parsed; namespace-scoped markers are not used in this repo.
var rbacMarker = regexp.MustCompile(`\+kubebuilder:rbac:groups=([^,]*),resources=([^,\s]*),verbs=([^,\s]*)`)

// controllerMarkerTriples reads every non-test Go file in dir and returns
// the (apiGroup, resource, verb) triples declared by csiControllerFile and
// by all other files. This mirrors what controller-gen feeds into
// config/rbac/role.yaml, but keeps the per-controller attribution the
// generated role flattens away.
func controllerMarkerTriples(t *testing.T, dir string) (csi, other map[ruleTriple]bool) {
	t.Helper()
	csi, other = map[ruleTriple]bool{}, map[ruleTriple]bool{}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read %s: %v", dir, err)
	}
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			t.Fatalf("read %s: %v", name, err)
		}
		into := other
		if name == csiControllerFile {
			into = csi
		}
		for _, m := range rbacMarker.FindAllStringSubmatch(string(data), -1) {
			for _, g := range strings.Split(m[1], ";") {
				// controller-gen accepts both spellings of the core group.
				if g = strings.Trim(g, `"`); g == "core" {
					g = ""
				}
				for _, res := range strings.Split(m[2], ";") {
					for _, v := range strings.Split(m[3], ";") {
						into[ruleTriple{apiGroup: g, resource: res, verb: v}] = true
					}
				}
			}
		}
	}
	return csi, other
}

// ruleTriple is one (apiGroup, resource, verb) grant. PolicyRule is a
// cross-product over its three slices, so we explode each rule into the
// triples it actually authorizes and compare those — comparing
// PolicyRule structs directly would falsely report drift on cosmetic
// differences like rule ordering or a single rule split into two for
// readability.
type ruleTriple struct {
	apiGroup string
	resource string
	verb     string
}

func (t ruleTriple) String() string {
	g := t.apiGroup
	if g == "" {
		g = `""`
	}
	return fmt.Sprintf(`apiGroups=%s resources=%s verbs=%s`, g, t.resource, t.verb)
}

func flattenRules(rules []rbacv1.PolicyRule) map[ruleTriple]bool {
	out := map[ruleTriple]bool{}
	for _, r := range rules {
		for _, g := range r.APIGroups {
			for _, res := range r.Resources {
				for _, v := range r.Verbs {
					out[ruleTriple{apiGroup: g, resource: res, verb: v}] = true
				}
			}
		}
	}
	return out
}

func helmManagerRules(t *testing.T, chartDir string, extraArgs ...string) []rbacv1.PolicyRule {
	t.Helper()
	// Render with the chart's default values unless the caller says
	// otherwise — exactly what `helm install seaweedfs/seaweedfs-operator`
	// produces for a fresh user. Rendering with feature toggles enabled
	// (e.g., serviceMonitor.enabled=true) would compare against the
	// unconditional kustomize role and mask any rule gated behind a
	// values flag — users hit the operator running with default-Helm
	// RBAC, and a rule that's only granted when a Helm flag is set
	// is effectively missing for them. The kustomize role represents
	// what the operator's controller code might actually request at
	// runtime; the chart's default render must be a superset of that,
	// regardless of which optional features the user toggles. RBAC
	// scoped to "only granted when feature X is enabled" is fine in
	// principle, but it has to be tied to a runtime signal the
	// operator code itself observes — not a Helm value the operator
	// binary knows nothing about. csiDriver.enabled is the one toggle
	// that qualifies: it is what sets ENABLE_CSI_DRIVER, so the
	// controller that needs the gated rules only runs when they are
	// granted. TestHelmManagerRoleCSIGate holds the two together.
	args := append([]string{"template", "drift-test", chartDir}, extraArgs...)
	cmd := exec.Command("helm", args...)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		// Distinguish a missing helm binary (legitimate skip on a
		// dev machine without helm) from a chart render error
		// (genuine regression that must fail the build).
		if errors.Is(err, exec.ErrNotFound) {
			t.Skipf("helm not found in PATH; skipping RBAC parity test: %v", err)
		}
		t.Fatalf("helm template failed: %v\nstderr: %s", err, stderr.String())
	}
	return findManagerRoleRules(t, stdout.Bytes(), "drift-test")
}

func findManagerRoleRules(t *testing.T, rendered []byte, releaseName string) []rbacv1.PolicyRule {
	t.Helper()
	dec := yaml.NewYAMLOrJSONDecoder(bytes.NewReader(rendered), 4096)
	wantName := releaseName + "-seaweedfs-operator-manager-role"
	for {
		var role rbacv1.ClusterRole
		if err := dec.Decode(&role); err != nil {
			if errors.Is(err, io.EOF) {
				break
			}
			// Skip docs that don't shape into a ClusterRole. Decode
			// returns errors for malformed YAML too, but the chart
			// is rendered fresh in the same test invocation and
			// already validated by helm template's own pass.
			continue
		}
		if role.Kind == "ClusterRole" && role.Name == wantName {
			return role.Rules
		}
	}
	t.Fatalf("no ClusterRole named %q found in rendered chart output (helm release: %q)", wantName, releaseName)
	return nil
}

func kustomizeManagerRules(t *testing.T, path string) []rbacv1.PolicyRule {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	var role rbacv1.ClusterRole
	if err := yaml.Unmarshal(data, &role); err != nil {
		t.Fatalf("unmarshal %s: %v", path, err)
	}
	if role.Kind != "ClusterRole" {
		t.Fatalf("%s: expected kind ClusterRole, got %q", path, role.Kind)
	}
	return role.Rules
}

// projectRoot finds the operator repo root by walking up from the test
// file's directory until it sees a go.mod. Lets the test run from any
// cwd (`go test ./test/helm/...` or invocation from the repo root).
func projectRoot(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller(0) failed")
	}
	dir := filepath.Dir(thisFile)
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatalf("could not find project root from %s", filepath.Dir(thisFile))
		}
		dir = parent
	}
}
