# permissions for end users to view seaweeds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: seaweed-viewer-role
rules:
- apiGroups:
  - seaweed.seaweedfs.com
  resources:
  - seaweeds
  - bucketclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - seaweed.seaweedfs.com
  resources:
  - seaweeds/status
  - bucketclaims/status
  verbs:
  - get
